/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Labing
 */
public class vistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public vistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuMaestro = new javax.swing.JMenu();
        MenuMaestroEmpleados = new javax.swing.JMenuItem();
        MenuCentroC = new javax.swing.JMenu();
        MenuCentroCostos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuConceptosPago = new javax.swing.JMenuItem();
        MenuConceptosDescuento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuComprobantes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuMaestro.setText("MaestroEmpleados");

        MenuMaestroEmpleados.setText("MaestroEmpleados");
        MenuMaestro.add(MenuMaestroEmpleados);

        jMenuBar1.add(MenuMaestro);

        MenuCentroC.setText("CentroCostos");

        MenuCentroCostos.setText("CentroCostos");
        MenuCentroC.add(MenuCentroCostos);

        jMenuBar1.add(MenuCentroC);

        jMenu1.setText("Conceptos");

        MenuConceptosPago.setText("Pago");
        MenuConceptosPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConceptosPagoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuConceptosPago);

        MenuConceptosDescuento.setText("Descuento");
        MenuConceptosDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConceptosDescuentoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuConceptosDescuento);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Comprobantes");

        MenuComprobantes.setText("Comprobantes");
        jMenu2.add(MenuComprobantes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");

        MenuSalir.setText("SALIR");
        jMenu3.add(MenuSalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuConceptosPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConceptosPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuConceptosPagoActionPerformed

    private void MenuConceptosDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConceptosDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuConceptosDescuentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MenuCentroC;
    public javax.swing.JMenuItem MenuCentroCostos;
    public javax.swing.JMenuItem MenuComprobantes;
    public javax.swing.JMenuItem MenuConceptosDescuento;
    public javax.swing.JMenuItem MenuConceptosPago;
    public javax.swing.JMenu MenuMaestro;
    public javax.swing.JMenuItem MenuMaestroEmpleados;
    public javax.swing.JMenuItem MenuSalir;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
